#!/usr/bin/env python3
"""Generate replacement positive norm weights, not recovered original data.

Only the header's positive decimal constants enter the proof. The approximate
orbit and Perron calculation optimize these freely chosen constants; they are
not certified data and make no enclosure claims. The core must independently
bound its logarithmic norms for these weights with directed rounding.
"""
import argparse
import json
import math
import re
from decimal import Decimal, localcontext
from fractions import Fraction
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
CORE=ROOT/'reference/core_tm_final2_t40.txt'
DEFAULT_HEADER=ROOT/'include/fixed_weight_schedule.hpp'

def rhs(t,x):
    A,p,C,d,Y,J=x
    D=t+C
    F=2*p*p/A+A*Y/(6*D)+A*d/(3*t*D)-p*d/D-C*p/(t*D)-2*p/D
    return (p,F,d,Y,J,6*t*F/A**3)

def rk4(t,x,h):
    k1=rhs(t,x)
    k2=rhs(t+h/2,[a+h*b/2 for a,b in zip(x,k1)])
    k3=rhs(t+h/2,[a+h*b/2 for a,b in zip(x,k2)])
    k4=rhs(t+h,[a+h*b for a,b in zip(x,k3)])
    return [a+h*(b+2*c+2*d+e)/6 for a,b,c,d,e in zip(x,k1,k2,k3,k4)]

def comparison(t,x):
    A,p,C,d,Y,J=x
    D=t+C
    F=rhs(t,x)[1]
    derivatives=[-2*p*p/A**2+Y/(6*D)+d/(3*t*D),
                 4*p/A-d/D-C/(t*D)-2/D,
                 -A*Y/(6*D**2)-A*d/(3*t*D**2)+p*d/D**2+p/D**2,
                 A/(3*t*D)-p/D,
                 A/(6*D),0.0]
    M=[[0.0]*6 for _ in range(6)]
    M[0][1]=M[2][3]=M[3][4]=M[4][5]=1.0
    M[1]=derivatives
    M[5]=[6*t/A**3*v for v in derivatives]
    M[5][0]-=18*t*F/A**4
    return [[v if i==j else abs(v) for j,v in enumerate(row)] for i,row in enumerate(M)]

def perron(M,initial=None):
    shift=1.0+max(0.0,max(-M[i][i] for i in range(6)))
    B=[[v+(shift if i==j else 0.0) for j,v in enumerate(row)] for i,row in enumerate(M)]
    q=list(initial or [1.0]*6)
    for iteration in range(20000):
        v=[sum(a*b for a,b in zip(row,q)) for row in B]
        qn=[z/v[-1] for z in v]
        error=max(abs(z/y-1) for z,y in zip(qn,q))
        q=qn
        if error<2e-14:break
    else:raise RuntimeError('Perron iteration failed')
    lam=sum(M[-1][j]*q[j] for j in range(6))
    residual=max(abs(sum(M[i][j]*q[j] for j in range(6))/q[i]-lam) for i in range(6))
    assert min(q)>0 and all(math.isfinite(v) for v in q)
    return q,lam,residual,iteration

def integration_nodes():
    # Reproduce caller's decimal coarse steps and substep count decisions.
    t=Fraction(20,19)
    target=Fraction(40)
    nodes=[t]
    coarse=0
    while t<target:
        td=float(t)
        hd=.005 if td<1.2 else .01 if td<1.5 else .02 if td<2 else .05 if td<4 else .1
        if td+hd>=float(target):
            h=target-t
            hd=float(h)
        else:h=Fraction(format(hd,'.17g'))
        maxsh=.0005 if td<1.2 else .002 if td<1.5 else .005 if td<2 else .01 if td<4 else .025 if td<10 else .05
        ns=math.ceil(hd/maxsh-1e-14)
        for ss in range(1,ns+1):nodes.append(t+h*ss/ns)
        t+=h
        coarse+=1
    return nodes,coarse

def read_center():
    text=CORE.read_text()
    state=[]
    with localcontext() as context:
        context.prec=100
        for name in ['A','p','C','d','Y','J']:
            found=re.search(rf'^{name} center \[([^,]+),([^\]]+)\]',text,re.M)
            state.append(float((Decimal(found[1])+Decimal(found[2]))/2))
    return state

def dstr(value):
    with localcontext() as context:
        context.prec=50
        return format(Decimal(value.numerator)/Decimal(value.denominator),'.40g')

def main():
    parser=argparse.ArgumentParser()
    parser.add_argument('--step',type=float,default=.0005)
    parser.add_argument('--header',type=Path,default=DEFAULT_HEADER)
    args=parser.parse_args()
    nodes,coarse=integration_nodes()
    state=read_center()
    time=40.0
    samples=[]
    lastq=None
    for node in reversed(nodes):
        goal=float(node)
        distance=time-goal
        n=max(1,math.ceil(distance/args.step)) if distance>0 else 0
        h=-distance/n if n else 0
        for k in range(n):
            state=rk4(time,state,h)
            time+=h
        time=goal
        q,lam,residual,iterations=perron(comparison(time,state),lastq)
        samples.append(dict(t=dstr(node),state=state.copy(),q=q,eigenvalue=lam,
                            relative_eigen_residual=residual,iterations=iterations))
        lastq=q
    samples.reverse()
    header='''#pragma once
// RECONSTRUCTED REPLACEMENT: the original weight schedule was not supplied.
// Generated by weights/generate_fixed_weights.py. These positive decimal
// rationals define freely chosen weighted infinity norms; they are not orbit
// enclosures. Every use of their associated logarithmic norm must be validated
// by the core caller's outward-rounded interval calculations.
'''
    header+=f'static constexpr int EW_QN = {len(samples)};\n'
    header+='static const char *const EW_T[EW_QN] = {\n'
    header+=''.join(f'  "{s["t"]}",\n' for s in samples)+'};\n'
    header+='static const char *const EW_Q[EW_QN][6] = {\n'
    header+=''.join('  {'+', '.join('"'+format(x,'.17g')+'"' for x in s['q'])+'},\n' for s in samples)+'};\n'
    args.header.parent.mkdir(parents=True,exist_ok=True)
    args.header.write_text(header)
    diagnostic=args.header.parent.parent/'weights/weight_generation_diagnostics.json'
    diagnostic.write_text(json.dumps(dict(generator='approximate backward RK4 and positive Perron weights',
         step=args.step,coarse_steps=coarse,substeps=len(samples)-1,samples=samples),indent=2)+'\n')
    print('Header:',args.header)
    print('Schedule nodes:',len(samples),'coarse steps:',coarse)
    print('t=start approximate state:',samples[0]['state'])
    print('t=start weights:',samples[0]['q'])
    print('t=40 weights:',samples[-1]['q'])
    print('Max relative eigen residual:',max(s['relative_eigen_residual'] for s in samples))

if __name__=='__main__':main()
