#!/usr/bin/env python3
"""Generate outward manuscript numbers from the current matching certificate.

No floating-point numbers enter the calculations. Pi is enclosed using the
alternating arctangent series and Machin's identity. Decimal table values are
rounded outwards from exact rational quantities.
"""
from contextlib import redirect_stdout
from fractions import Fraction as Q
import io
import json
from pathlib import Path
import re
import runpy
import sys

ROOT=Path(__file__).resolve().parents[2]
FRAGMENTS=ROOT.parent/'fragments'

def integer_ceiling(x):return -((-x.numerator)//x.denominator)

def fixed(x,places,direction):
    scaled=x*10**places
    integer=scaled.numerator//scaled.denominator if direction=='down' else integer_ceiling(scaled)
    sign='-' if integer<0 else ''
    whole,frac=divmod(abs(integer),10**places)
    return f'{sign}{whole}.{frac:0{places}d}'

def scientific(x,digits,direction):
    assert x>0
    exponent=len(str(x.numerator))-len(str(x.denominator))
    while x<Q(10)**exponent:exponent-=1
    while x>=Q(10)**(exponent+1):exponent+=1
    mantissa=fixed(x/(Q(10)**exponent),digits-1,direction)
    return rf'{mantissa}\times10^{{{exponent}}}'

def arctan_interval(inverse,n):
    x=Q(1,inverse)
    partial=sum((-1)**j*x**(2*j+1)/Q(2*j+1) for j in range(n))
    next_term=(-1)**n*x**(2*n+1)/Q(2*n+1)
    return min(partial,partial+next_term),max(partial,partial+next_term)

def pi_interval():
    a_lo,a_hi=arctan_interval(5,90)
    b_lo,b_hi=arctan_interval(239,30)
    return 16*a_lo-4*b_hi,16*a_hi-4*b_lo

def ratio_record(x):return {'numerator':str(x.numerator),'denominator':str(x.denominator)}

def source_decimal(source,name):
    """Read one exact decimal constructor, independent of C++ line wrapping."""
    matches=re.findall(rf'\b{re.escape(name)}\s*\(\s*"([^"]+)"\s*\)',source)
    if len(matches)!=1:
        raise ValueError(f'Expected one decimal initializer for {name}; found {len(matches)}')
    return Q(matches[0])

def main():
    core=Path(sys.argv[1]).resolve() if len(sys.argv)>1 else ROOT/'logs/core_reconstructed.txt'
    old_argv=sys.argv
    sys.argv=[str(Path(__file__).with_name('poincare_certificate.py')),str(core)]
    capture=io.StringIO()
    try:
        with redirect_stdout(capture):data=runpy.run_path(sys.argv[0])
    finally:sys.argv=old_argv
    (ROOT/'logs/poincare_revised.txt').write_text(capture.getvalue())
    source=(ROOT/'src/verified_core_taylor_model.repaired.cpp').read_text()
    b=source_decimal(source,'b0')
    R=source_decimal(source,'R0')
    A,beta,eta=data['Ainf'],data['beta'],data['eta']
    rb,rR,rA,rbeta,reta=data['radii']
    pi_lo,pi_hi=pi_interval()
    assert 3<pi_lo<pi_hi<4
    bounds={
      'B':(b-rb,b+rb,55),
      'R':(R-rR,R+rR,55),
      'Mass':(-(beta+rbeta)/(2*(A+rA)),-(beta-rbeta)/(2*(A-rA)),34),
      'Temperature':((A-rA)/(4*pi_hi*(R+rR)),(A+rA)/(4*pi_lo*(R-rR)),34),
      'Entropy':(pi_hi*(-1-2*(b+rb)),pi_lo*(-1-2*(b-rb)),50),
    }
    FRAGMENTS.mkdir(parents=True,exist_ok=True)
    macros=['% Generated by ancillary/python/matching/generate_paper_data.py; exact rational outward rounding.']
    manifest={'parameter_order':['b','R','A_infinity','beta','eta'],
              'centers':[str(x) for x in (b,R,A,beta,eta)],'radii':[str(x) for x in data['radii']],
              'pi_interval':[ratio_record(pi_lo),ratio_record(pi_hi)],'physical_bounds':{},
              'matching_margins':[]}
    for name,(lo,hi,places) in bounds.items():
        lower,upper=fixed(lo,places,'down'),fixed(hi,places,'up')
        assert Q(lower)<=lo<hi<=Q(upper)
        macros.extend([r'\newcommand{\Certified'+name+'Lower}{'+lower+'}',
                       r'\newcommand{\Certified'+name+'Upper}{'+upper+'}'])
        manifest['physical_bounds'][name]={'lower':ratio_record(lo),'upper':ratio_record(hi),
                                           'display_lower':lower,'display_upper':upper}
    margins=[m/r for m,r in zip(data['margin'],data['radii'])]
    macros.append(r'\newcommand{\CertifiedMarginMinimum}{'+fixed(min(margins),16,'down')+'}')
    (FRAGMENTS/'generated_bounds.tex').write_text('\n'.join(macros)+'\n')
    rows=[]
    for i,(radius,center,error,margin) in enumerate(zip(data['radii'],data['g0'],data['gerr'],margins),1):
        rows.append(f'{i} & ${scientific(radius,2,"up")}$ & '
                    f'${scientific(abs(center),5,"up")}$ & '
                    f'${scientific(error,5,"up")}$ & ${fixed(margin,12,"down")}$ \\\\')
        manifest['matching_margins'].append(ratio_record(margin))
    table=r'''% Generated outward numerical table. Nominal g0 differs from the exact G(theta0).
\begin{table}[ht]
\centering
\begin{tabular}{@{}ccccc@{}}
\toprule
$i$ & $r_i$ & $|g_{0,i}|$ & $E_i$ & $m_i/r_i$ \\
\midrule
'''+ '\n'.join(rows)+r'''
\bottomrule
\end{tabular}
\caption{Poincar\'e--Miranda face bounds from the regenerated core. The radius is exact;
the displacement and error are rounded upward, and the normalized margin downward.
The unrounded quantities are rational numbers in the certificate.}
\label{tab:poincare-full}
\end{table}
'''
    (FRAGMENTS/'matching_table.tex').write_text(table)
    (ROOT/'logs/paper_data.json').write_text(json.dumps(manifest,indent=2)+'\n')
    print('PASS: generated outward parameter, mass, temperature, literal-action entropy, and matching data.')
    print('Minimum normalized matching margin:',fixed(min(margins),16,'down'))
    print('Generated fragments:',FRAGMENTS)

if __name__=='__main__':main()
